In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3,4])
b = np.array([[1,2,3,4],[2,3,4,5]])
c = np.array([[1,2,3,4,3],[3,4,5,6,7],[4,5,6,8,9]])


In [6]:
print(a.ndim)
print(b.ndim)
b.dtype

1
2


dtype('int32')

In [7]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)
b.shape
b.size

[[1 2 3 4]
 [5 6 7 8]]


8

In [8]:
b = np.array([[1,2,3,4,9,11],[2,3,4,5,13,15]])
print(b)

[[ 1  2  3  4  9 11]
 [ 2  3  4  5 13 15]]


In [30]:
b[0,:]
b[:,3]

array([4, 5])

In [34]:
b[1, 0:-1:2]

array([ 2,  4, 13])

In [9]:
b[1,3] = 200
print(b)

[[  1   2   3   4   9  11]
 [  2   3   4 200  13  15]]


In [39]:
b[1, :] = 1
print(b)

[[ 1  2  1  4  9 11]
 [ 1  1  1  1  1  1]]


In [10]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
ar = np.array([[[1,2,3], [4,5,6]],[[7,8,9],[10,11,12]]])
print(ar)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [17]:
ar[1,1,1]

IndexError: index 2 is out of bounds for axis 0 with size 2